### PR TITLE
CPFP Fee Calculation Bug Fix and UI Improvements

### LINKED ISSUE #424: Adjust language in CPFP flow
Please see attached images below, and ignore the red boxes.

My original parent transaction was ~5 sat/vb, and the first image suggests the current high fee rate is ~33 sat/vb. Therefore the child transaction needs to be ~68 sat/vb to result in an effective fee rate of ~33 sat/vb (I'm assuming this is the target) for both transactions.

That was my first interpretation.

However things got confusing on the second image. It says in two separate places that the "target combined fee rate" is ~68 sat/vb. That doesn't make sense, if ~68 sat/vb is what is being used for the child transaction only. Yet the math 23,445 sats ÷ 360 vb does check out. 

So I'm seeing a couple issues:
1) Why is the "target combined fee rate" (which I would suggest renaming to "target effective fee rate" to match verbiage on mempool.space) double the high fee rate of 33 sat/vb? I would think it should be barely above it, like 35 sat/vb or 40 sat/vb.

2) I think we should also be explicitly displaying the fee rate being used for the child transaction. This will, after all, be the fee rate someone sees after loading up the PSBT file that was created by this feature. For this transaction I calculate the child transaction used 147.5 sat/vb (23455 sats ÷ 159 vb).

Image

Image

### PR DESCRIPTION
**Pull request by Legend101Zz**
### Critical Bug Fixed

FIxes #424 

Fixed the `minimumCPFPFee` calculation bug identified by @tomunchained  that was causing users to overpay by alot ... 

**The Issue:**
- `cpfpFeeRate` correctly calculated the child transaction's required fee rate (e.g., 68 sat/vB)
- `minimumCPFPFee` then incorrectly multiplied this by `CPFPPackageSize` (parent + child) instead of just `estimatedCPFPChildSize`
- Result: Child paid fees for the entire package at target rate, doubling the effective fee rate
  - Expected: 33 sat/vB combined effective rate
  - Actual: 68 sat/vB combined effective rate

**The Fix:**
Changed `minimumCPFPFee` to multiply `cpfpFeeRate` by `estimatedCPFPChildSize` only, ensuring the child pays just the additional fee needed to reach the target package rate.

### UI Improvements

**Strategy Selection Screen:**
- Added child-specific labels for CPFP ("Child transaction fee" vs generic "Minimum fee required")
- Added tooltip explaining CPFP formula: `(TargetRate × TotalSize - ParentFee) / ChildSize`
- Shows target fee rate is set to current network medium rate
- Caption explains combined effective rate goal

**CPFP Configuration Form:**
- Slider now controls child transaction fee rate directly (not combined rate)
- Displays three distinct rates:
  - Parent fee rate (existing transaction)
  - Child fee rate (new transaction being created)
  - Combined effective rate (package rate miners evaluate)
- Updated slider label from "Target Combined Fee Rate" to "Child Transaction Fee Rate"
- Minimum slider value starts at calculated minimum child fee rate from `cpfp.feeRate`

**Credit:** Thanks to @tomunchained for identifying and documenting the bug, and for the detailed analysis and solution :)

Screenshot 2026-01-01 at 19 34 51
Screenshot 2026-01-01 at 19 35 17

Screenshot 2026-01-01 at 22 34 17

### CODE REVIEW

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ConfigurationStep/CPFP/CPFPForm.tsx [hunk 1]
```diff
@@ -246,20 +265,23 @@ export const CPFPForm: React.FC = () => {
...
-          minimumFeeRate={minimumFeeRate}
+          minimumFeeRate={minimumChildFeeRate}
           maxFeeRate={maxFeeRate}
           feeEstimates={feeEstimates || {}}
         />
 
         <Box sx={{ mt: 2 }}>
           <Typography variant="body2" color="text.secondary">
-            Parent fee rate: {originalFeeRate.toFixed(1)} sats/vB
+            Parent fee rate: {originalFeeRate.toFixed(2)} sats/vB
```
Comment (bucko13) [inline apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ConfigurationStep/CPFP/CPFPForm.tsx]: was the `toFixed(1)` causing issues.

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/StrategySelectionStep/StrategyRadioGroup.tsx [hunk 2]
```diff
@@ -173,24 +176,112 @@ export const StrategyRadioGroup: React.FC<StrategyRadioGroupProps> = ({
...
-                        </Typography>
-                      </Grid>
-                      <Grid item xs={6}>
-                        <Typography variant="body2" color="text.secondary">
-                          Suggested fee rate:
-                        </Typography>
-                        <Typography variant="body2">
-                          {config.suggestedFeeRate.toFixed(2)} sats/vB
+                    {config.strategy === "CPFP" ? (
+                      <>
```
Comment (bucko13) [inline apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/StrategySelectionStep/StrategyRadioGroup.tsx]: can we pull these out into their own component? I think it'll help make this a little more readable.

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/hooks.ts [hunk 3]
```diff
@@ -129,6 +134,7 @@ export const useAnalyzeTransaction = (
           feeRate: analyzer.cpfpFeeRate,
           childSize: analyzer.estimatedCPFPChildSize,
           estimatedPackageSize: analyzer.CPFPPackageSize,
+          targetFeeRate: targetFeeRate,
```
Comment (bucko13) [inline apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/hooks.ts]:
```suggestion
          targetFeeRate,
```

File: .changeset/busy-poems-sit.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+"@caravan/transactions": patch
```
Comment (bucko13) [inline .changeset/busy-poems-sit.md]: I haven't published yet so no need to add this. (I really should though and publish it as a v1)

File: packages/transactions/src/transactionAnalyzer.ts [hunk 5]
```diff
@@ -394,8 +396,10 @@ export class TransactionAnalyzer {
    *                     transaction's fee is already sufficient for the desired rate.
    */
   get minimumCPFPFee(): Satoshis {
+    // so we want to know the extra fees that child has to pay,
+    // remember when miner takes in this tx ( along with the parent) they are rewarded minimumCPFPFee + ParentFee
```
Comment (bucko13) [inline packages/transactions/src/transactionAnalyzer.ts]:
```suggestion
    // remember when miner takes in this tx (along with the parent) they are rewarded minimumCPFPFee + ParentFee
```

**Review by bucko13 — CHANGES_REQUESTED** [review]
Nothing crazy in my comments. Mostly nits. Thanks for the fixes!

**Comment by Legend101Zz** [comment]
> Lastly, super small nit, but the PSBT I downloaded has a fee that is off by one satoshi. 11584 instead of 11583. It might just be some type of rounding issue. Probably not worth spending much time on unless it can be identified and fixed super easliy.

Thanks a ton for testing it out ... I'll make the UI changes you suggested for the last ( Review Step) page as you suggested :)

> Lastly, super small nit, but the PSBT I downloaded has a fee that is off by one satoshi. 11584 instead of 11583. It might just be some type of rounding issue. Probably not worth spending much time on unless it can be identified and fixed super easliy.


Ahh, good catch ... 
This is actually a fairly hard thing to avoid, and in this case `11584` is technically more accurate than the `11583` shown in the UI.

What’s happening is that the UI performs a few rounding steps when displaying fee-related values, based on the data we get from the `caravan/transaction` package (especially around fee bumping). Those rounded values are what end up being surfaced to the user.

Under the hood though, what we ultimately pass to the `caravan/transaction` package is just the final `targetFeeRate` selected by the user. The actual fee calculation and PSBT construction then happen downstream with full precision, which is why you can occasionally see a ±1 sat difference.

So you’re right—it’s essentially a rounding / display artifact on the UI side  ... honestly let me check if I can have it fixed by using `BigNumber` lib operations instead of normal JS ops ( on the UI side(

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/StrategySelectionStep/StrategyRadioGroup.tsx (hunk 2 above)
Comment (Legend101Zz) [reply apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/StrategySelectionStep/StrategyRadioGroup.tsx]: sure , done https://github.com/caravan-bitcoin/caravan/pull/441/commits/74e838a6cca476c3b220ed4dac1749008c991bfb :)

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/hooks.ts [hunk 6]
```diff
@@ -111,9 +118,7 @@ export const useAnalyzeTransaction = (
       const analyzer = new TransactionAnalyzer({
         txHex,
         network: network as Network,
-        targetFeeRate:
-          feeEstimates[FeePriority.MEDIUM] ??
-          (transaction.vsize ? transaction.fee / transaction.vsize : 250),
+        targetFeeRate: targetFeeRate,
```
[the remark this answers is not in the document]
Comment (Legend101Zz) [reply apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/hooks.ts]: done https://github.com/caravan-bitcoin/caravan/pull/441/commits/daf47b5dbba843deb48b96e949a9515a6a9ca6d1

File: .changeset/busy-poems-sit.md (hunk 4 above)
Comment (Legend101Zz) [reply .changeset/busy-poems-sit.md]: done https://github.com/caravan-bitcoin/caravan/pull/441/commits/07d6db75b8c68865fd4a1e9344f384f7b437600e

**Review by bucko13 — DISMISSED** [review]
Code approved. Will wait to merge after @tomunchained gives a final thumbs up.

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ReviewStep/TransactionComparison.tsx [hunk 7]
```diff
@@ -17,7 +17,7 @@ import { FeeBumpStrategy } from "@caravan/transactions";
 import { useAccelerationModal } from "../../AccelerationModalContext";
 import { RBF_TYPES } from "../../../types";
 
-import { TransactionComparisonTable } from "./TransactionComparisonTable ";
```
Comment (Legend101Zz) [inline apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ReviewStep/TransactionComparison.tsx]: seems like the file name had a space char init , so I renamed that file :)

**Comment by bucko13** [comment]
I think [this](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R104) is where the confusion is coming from. The column name in code is `difference`, but the column title is `Package Total`. I think you probably just want to change [this line](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R268) so that it's `<strong>{isCPFP ?  : "Difference": "Package Total"}</strong>` and then have the `fees` row also show a difference instead of total OR you can flip it and show `Package Total`, remove `Total:` [here](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R112), and then recalculate the fee rate row value to calculate the total fee rate (which should be `(fee_A + fee_B) / (pk_A_size + pk_B_size)`

**Comment by Legend101Zz** [comment]
> I think [this](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R104) is where the confusion is coming from. The column name in code is `difference`, but the column title is `Package Total`. I think you probably just want to change [this line](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R268) so that it's `\<strong\>{isCPFP ? : "Difference": "Package Total"}\</strong\>` and then have the `fees` row also show a difference instead of total OR you can flip it and show `Package Total`, remove `Total:` [here](https://github.com/caravan-bitcoin/caravan/pull/441/files#diff-b44d0cad60eb562944a672746bb59f2a62fbe4a2d92c0c412a5bf7dd09598309R112), and then recalculate the fee rate row value to calculate the total fee rate (which should be `(fee_A + fee_B) / (pk_A_size + pk_B_size)`

Yup calculation like this :) , let me try

File: apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ReviewStep/TransactionComparisonTable.tsx [hunk 8]
```diff
@@ -124,7 +131,33 @@ export const TransactionComparisonTable: React.FC<TransactionComparisonTableProp
...
+
+                    const childFee = packageFee.minus(parentFee);
+                    const childFeeRate = new BigNumber(
+                      feeBumpResult.newFeeRate,
+                    );
+
+                    // size = fee / fee_rate
+                    const parentSize = parentFee.dividedBy(parentFeeRate);
+                    const childSize = childFee.dividedBy(childFeeRate);
+                    console.log(
```
[the remark this answers is not in the document]
Comment (Legend101Zz) [reply apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/components/FeeBumpSteps/ReviewStep/TransactionComparisonTable.tsx]: changes done https://github.com/caravan-bitcoin/caravan/pull/441/commits/7d82c05735bb7e427bcbb52c800c454b094f8812 :)
