### PR TITLE
Fix error on address generator

### LINKED ISSUE #72: Bug: Error when selecting Ledger or Trezor in address generator
**Current Behavior**
When we go to address generator and select method for public key as Ledger or Trezor error shows up
Screenshot from 2024-04-16 20-19-41

**Steps to Reproduce (for bugs)**
Go to Address
Select Ledger or Trezor as public key method
Note you will see error

**Environment**
Where are you running caravan: localhost
Operating system: Linux
Browser and version: Chrome

### PR DESCRIPTION
**Pull request by bucko13**
fix interactions call in HardwareWalletPublicKeyImporter.

Fixes #72

### CODE REVIEW

File: apps/coordinator/src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx [hunk 1]
```diff
@@ -160,7 +160,7 @@ const HardwareWalletPublicKeyImporter = ({
           </Button>
         </Box>
         <InteractionMessages
-          messages={interaction.messagesFor({ state: status })}
+          messages={interaction().messagesFor({ state: status })}
```
Comment (benthecarman) [inline apps/coordinator/src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx:163]: javascript was a mistake lmao

Comment (bucko13) [reply apps/coordinator/src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx:163]: You're right. Typescript is the solution! 🎉 

Getting there in caravan.
